spring:
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/employee_directory

# spring data rest api base path
  data:
    rest:
      base-path: /api
      default-page-size: 20